import '../models/pokemon_card.dart';

class MockCatalog {
  static List<PokemonCard> getCards() {
    return [
      PokemonCard(
        id: 'p-001',
        name: 'Charizard ex',
        type: 'Fire',
        rarity: 'Ultra Rare',
        marketPrice: 120.00,
        priceHistory: [115.0, 118.0, 116.5, 122.0, 120.5, 119.0, 120.0],
        description: 'It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.',
        imageUrl: 'https://images.pokemontcg.io/sv3pt5/199_hires.png',
        hp: 330,
        attackName: 'Explosive Vortex',
        attackDamage: 330,
        weakness: 'Water x2',
        retreatCost: 2,
      ),
      PokemonCard(
        id: 'p-002',
        name: 'Pikachu ex',
        type: 'Lightning',
        rarity: 'Ultra Rare',
        marketPrice: 95.00,
        priceHistory: [88.0, 90.0, 92.5, 91.0, 93.5, 94.0, 95.0],
        description: 'When it smashes its opponent with its electrified tail, it discharges electricity equal to a lightning bolt.',
        imageUrl: 'https://images.pokemontcg.io/sv8/65_hires.png',
        hp: 200,
        attackName: 'Pika Bolt',
        attackDamage: 220,
        weakness: 'Fighting x2',
        retreatCost: 1,
      ),
      PokemonCard(
        id: 'p-003',
        name: 'Mewtwo ex',
        type: 'Psychic',
        rarity: 'Secret Rare',
        marketPrice: 180.00,
        priceHistory: [170.0, 172.5, 175.0, 174.0, 178.5, 179.0, 180.0],
        description: 'A Pokémon created by recombining Mew\'s genes. It\'s said to have the most savage heart among Pokémon.',
        imageUrl: 'https://images.pokemontcg.io/sv4pt5/205_hires.png',
        hp: 230,
        attackName: 'Psyburn Pulse',
        attackDamage: 180,
        weakness: 'Dark x2',
        retreatCost: 2,
      ),
      PokemonCard(
        id: 'p-004',
        name: 'Blastoise ex',
        type: 'Water',
        rarity: 'Rare Holo',
        marketPrice: 65.00,
        priceHistory: [60.0, 62.0, 61.5, 64.0, 63.0, 64.5, 65.0],
        description: 'It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.',
        imageUrl: 'https://images.pokemontcg.io/sv3pt5/200_hires.png',
        hp: 340,
        attackName: 'Twin Cannon',
        attackDamage: 280,
        weakness: 'Lightning x2',
        retreatCost: 3,
      ),
      PokemonCard(
        id: 'p-005',
        name: 'Venusaur ex',
        type: 'Grass',
        rarity: 'Rare Holo',
        marketPrice: 55.00,
        priceHistory: [58.0, 57.0, 56.5, 55.0, 54.0, 55.5, 55.0],
        description: 'A bewitching aroma wafts from its flower. The fragrance becalms those engaged in a battle.',
        imageUrl: 'https://images.pokemontcg.io/sv3pt5/198_hires.png',
        hp: 340,
        attackName: 'Forest Storm',
        attackDamage: 150,
        weakness: 'Fire x2',
        retreatCost: 4,
      ),
      PokemonCard(
        id: 'p-006',
        name: 'Umbreon Star',
        type: 'Dark',
        rarity: 'Secret Rare',
        marketPrice: 350.00,
        priceHistory: [340.0, 342.0, 345.5, 348.0, 346.0, 349.0, 350.0],
        description: 'When exposed to the moon\'s aura, the rings on its body glow faintly, and it gains a mysterious power.',
        imageUrl: 'https://images.pokemontcg.io/cel25/17_hires.png',
        hp: 100,
        attackName: 'Dark Ring',
        attackDamage: 120,
        weakness: 'Fighting x2',
        retreatCost: 1,
      ),
      PokemonCard(
        id: 'p-007',
        name: 'Lugia ex',
        type: 'Colorless',
        rarity: 'Ultra Rare',
        marketPrice: 110.00,
        priceHistory: [105.0, 107.0, 106.5, 109.0, 108.5, 111.0, 110.0],
        description: 'It is said that a flutter of its wings creates a tempest. As a result, this Pokémon keeps itself deep underwater.',
        imageUrl: 'https://images.pokemontcg.io/sit/186_hires.png',
        hp: 250,
        attackName: 'Aero Dive',
        attackDamage: 220,
        weakness: 'Lightning x2',
        retreatCost: 2,
      ),
      PokemonCard(
        id: 'p-008',
        name: 'Gengar ex',
        type: 'Psychic',
        rarity: 'Rare Holo',
        marketPrice: 75.00,
        priceHistory: [72.0, 73.5, 75.0, 74.0, 73.0, 76.5, 75.0],
        description: 'Under a full moon, this Pokémon likes to shadow people and laugh at their fright.',
        imageUrl: 'https://images.pokemontcg.io/sv5/104_hires.png',
        hp: 310,
        attackName: 'Trick Step',
        attackDamage: 160,
        weakness: 'Dark x2',
        retreatCost: 2,
      ),
      PokemonCard(
        id: 'p-009',
        name: 'Rayquaza VMAX',
        type: 'Colorless',
        rarity: 'Secret Rare',
        marketPrice: 280.00,
        priceHistory: [265.0, 270.0, 275.5, 272.0, 278.0, 282.5, 280.0],
        description: 'It flies endlessly in the ozone layer. It is said that it would descend to the ground if Groudon and Kyogre were to fight.',
        imageUrl: 'https://images.pokemontcg.io/swsh7/218_hires.png',
        hp: 320,
        attackName: 'Max Burst',
        attackDamage: 340,
        weakness: 'None',
        retreatCost: 2,
      ),
    ];
  }
}
