// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFfwwaA-KijI7gSLos752aJ31E2GUAvKo',
    appId: '1:684638928442:web:7f2e858c06acf4cea5ff03',
    messagingSenderId: '684638928442',
    projectId: 'tcg-collector-55418',
    authDomain: 'tcg-collector-55418.firebaseapp.com',
    storageBucket: 'tcg-collector-55418.firebasestorage.app',
    measurementId: 'G-84YKPVEKQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKJ4A12caw0aXSOnxSfHhR7R2bDmT1IYg',
    appId: '1:684638928442:android:fdc890b8d15046fca5ff03',
    messagingSenderId: '684638928442',
    projectId: 'tcg-collector-55418',
    storageBucket: 'tcg-collector-55418.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFfwwaA-KijI7gSLos752aJ31E2GUAvKo',
    appId: '1:684638928442:web:5af568af8fb4d19ea5ff03',
    messagingSenderId: '684638928442',
    projectId: 'tcg-collector-55418',
    authDomain: 'tcg-collector-55418.firebaseapp.com',
    storageBucket: 'tcg-collector-55418.firebasestorage.app',
    measurementId: 'G-9Z0PPM92W9',
  );
}
